USE --<INSERT DB_NAME>--
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*SAMPLE DATA --
    JSON FORMAT TO FOLLOW: {
	"ARCHV_DTL": {"ARCHV_IN_DAYS": 90, "DATE_FILTER":"CHG_DTM", "ARCHVL_PROC": "", "COLUMN_FILTER": "IS_PRCSSD = 2 AND STS=''Processed''"}, 
	"PURGE_DTL": {"PURGE_IN_DAYS": 365, "DATE_FILTER":"CHG_DTM", "COLUMN_FILTER": "IS_PRCSSD = 2 AND STS=''Processed''"}}
*/

--IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LOG_ARCHVL_PRG_TBL_DTL')
--BEGIN
-- DECLARE @CRE_EMP_WWID NVARCHAR(256) = 99999999 , @CRE_DTM DATETIME = GETDATE()
-- INSERT INTO [DBO].[LOG_ARCHVL_PRG_TBL_DTL] (
--     [DB_NAME], [LOG_TBL_NM], [PURGE_IN_DAYS], [IS_ARCHV] ,[ARCHV_IN_DAYS], [ARCHV_DB_NAME], [ARCHV_TBL_NM], [JSON_COND], [ACTV_IND], [CRE_DTM], [CRE_EMP_WWID], [CHG_DTM], [CHG_EMP_WWID]
-- )
-- VALUES
-- (10, 'MYDEALS', 'DBO', 'BTCH_LD_LOG', 1, 1, 'MYDEALS_FILE', 'DBO', 'BTCH_LD_LOG_ARCHV', '{"ARCHV_DTL": {"ARCHV_IN_DAYS": 90, "DATE_FILTER":"CHG_DTM"}, "PURGE_DTL": {"PURGE_IN_DAYS": 365, "DATE_FILTER":"CHG_DTM"}}', 1)
--END