USE --<INSERT DB_NAME>--
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LOG_ARCHVL_PRG_TBL_DTL')
BEGIN
    CREATE TABLE [DBO].[LOG_ARCHVL_PRG_TBL_DTL](
        [LOG_ARCHVL_PRG_TBL_DTL_SID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
		[SRT_ORDR] INT NOT NULL,
        [DB_NAME] [varchar](128) NOT NULL,
		[SCHEMA] [varchar](128) NOT NULL,
        [LOG_TBL_NM] [nvarchar](500) NOT NULL,
		[IS_PURGE] BIT NOT NULL DEFAULT 0,
		[IS_ARCHV] BIT NOT NULL DEFAULT 0,
		[ARCHV_DB_NAME] [varchar](128) NULL,
		[ARCHV_SCHEMA] [varchar](128) NULL,
        [ARCHV_TBL_NM] [nvarchar](500) NULL,
		[VIEW_NM] [nvarchar](500) NULL,
        [JSON_COND] [nvarchar](MAX) NULL,
		[ACTV_IND] [bit] NOT NULL DEFAULT 1,
		[STATUS] [nvarchar](MAX) DEFAULT 'NOT RUN',
		[LST_RUN] [datetime] NULL,
        [CRE_DTM] [datetime] NOT NULL DEFAULT GETDATE(),
        [CRE_EMP_WWID] INT NOT NULL DEFAULT 99999999,
        [CHG_DTM] [datetime] NOT NULL DEFAULT GETDATE(),
        [CHG_EMP_WWID] INT NOT NULL DEFAULT 99999999,
		CONSTRAINT UQ_SRT_ORDR UNIQUE ([SRT_ORDR]),
		CONSTRAINT UQ_LOG_ARCHVL_PRG_TBL_DTL UNIQUE ([DB_NAME], [SCHEMA], [LOG_TBL_NM]),
		CONSTRAINT CHK_JSON_COND CHECK (ISJSON([JSON_COND])=1),	
		CONSTRAINT CHK_ARCHV_TBL_DTL CHECK (([ARCHV_DB_NAME] IS NOT NULL AND [ARCHV_SCHEMA] IS NOT NULL AND [ARCHV_TBL_NM] IS NOT NULL) 
		OR ([ARCHV_DB_NAME] IS NULL AND [ARCHV_SCHEMA] IS NULL AND [ARCHV_TBL_NM] IS NULL))
		);
END
 
-- SAMPLE DATA --
	-- JSON FORMAT TO FOLLOW: {
	--"ARCHV_DTL": {"ARCHV_IN_DAYS": 90, "DATE_FILTER":"CHG_DTM", "ARCHVL_PROC": "", "COLUMN_FILTER": "IS_PRCSSD = 2 AND STS=''Processed''"}, 
	--"PURGE_DTL": {"PURGE_IN_DAYS": 365, "DATE_FILTER":"CHG_DTM", "COLUMN_FILTER": "IS_PRCSSD = 2 AND STS=''Processed''"}}

-- DECLARE @CRE_EMP_WWID NVARCHAR(256) = 99999999
--         , @CRE_DTM DATETIME = GETDATE()
-- INSERT INTO [DBO].[LOG_ARCHVL_PRG_TBL_DTL] (
--     [DB_NAME], [LOG_TBL_NM], [PURGE_IN_DAYS], [IS_ARCHV] ,[ARCHV_IN_DAYS], [ARCHV_DB_NAME], [ARCHV_TBL_NM], [JSON_COND], [ACTV_IND], [CRE_DTM], [CRE_EMP_WWID], [CHG_DTM], [CHG_EMP_WWID]
-- )
-- VALUES
-- (10, 'MYDEALS', 'DBO', 'BTCH_LD_LOG', 1, 1, 'MYDEALS_FILE', 'DBO', 'BTCH_LD_LOG_ARCHV', '{"ARCHV_DTL": {"ARCHV_IN_DAYS": 90, "DATE_FILTER":"CHG_DTM"}, "PURGE_DTL": {"PURGE_IN_DAYS": 365, "DATE_FILTER":"CHG_DTM"}}', 1)
