USE --<INSERT DB_NAME>--
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LOG_ARCHVL_PRG_TBL_DTL_HIST')					  
BEGIN
	CREATE TABLE [DBO].[LOG_ARCHVL_PRG_TBL_DTL_HIST](
		[LOG_ARCHVL_PRG_TBL_DTL_SID] [int] NOT NULL,
		[SRT_ORDR] INT NOT NULL,
        [DB_NAME] [varchar](128) NOT NULL,
		[SCHEMA] [varchar](128) NOT NULL,
        [LOG_TBL_NM] [nvarchar](500) NOT NULL,
		[IS_PURGE] BIT NOT NULL,
		[IS_ARCHV] BIT NOT NULL,
		[ARCHV_DB_NAME] [varchar](128) NULL,
		[ARCHV_SCHEMA] [varchar](128) NULL,
        [ARCHV_TBL_NM] [nvarchar](500) NULL,
		[VIEW_NM] [nvarchar](500) NULL,
        [JSON_COND] [nvarchar](MAX) NULL,
		[ACTV_IND] [bit] NOT NULL,
		[STATUS] [nvarchar](MAX) NULL,
		[LST_RUN] [datetime] NULL,
		[CRE_DTM] [datetime] NOT NULL,
        [CRE_EMP_WWID] INT NOT NULL,
        [CHG_DTM] [datetime] NOT NULL,
        [CHG_EMP_WWID] INT NOT NULL,
		[HIST_EFF_FR_DTM] DATETIME NOT NULL,
		[HIST_EFF_TO_DTM] DATETIME NOT NULL			
	);
END